FROM node:24-bookworm

RUN corepack enable \
  && corepack prepare pnpm@9.15.0 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

# Start dev server
CMD ["pnpm", "run", "dev"]
