FROM ubuntu:22.04

# Update package lists and install necessary dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        curl \
        gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Set working directory
WORKDIR /app

# Copy dependencies
COPY package.json ./

# Install dependencies 
RUN npm cache clean --force
RUN npm install --include=optional

# Expose the port for development server
EXPOSE 3000

# Copy the code
COPY . .

# Start the development server with watch mode and volume mapping
CMD ["npm", "run", "dev"]

