version: "3.8"

services:
  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # So Traefik can listen to the Docker events
      - "./letsencrypt:/letsencrypt" # Persistent volume for certificates
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    restart: always
  # ------------------- APPS ------------------
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_URL_SNAPSHOT_HANDLER=${URL_SNAPSHOT_HANDLER}
      - NEXT_PUBLIC_URL_BABYBOX_SERVICE=${URL_BABYBOX_SERVICE}
      - NEXT_PUBLIC_URL_USER_SERVICE=${URL_USER_SERVICE}
    restart: always
    depends_on:
      - snapshot-handler

  snapshot-handler:
    build:
      context: ./apps/snapshot-handler
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snapshot-handler.entrypoints=web"
      - "traefik.http.routers.snapshot-handler.rule=Host(`snapshot-handler.${DOMAIN}`)"
    depends_on:
      - rabbitmq
      - influxdb

  babybox-service:
    build:
      context: ./apps/babybox-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.babybox-service.entrypoints=web"
      - "traefik.http.routers.babybox-service.rule=Host(`babybox-service.${DOMAIN}`)"
    depends_on:
      - rabbitmq
      - mongodb

  user-service:
    build:
      context: ./apps/user-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - APP_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - DEFAULT_USERNAME=${DEFAULT_USERNAME}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service.entrypoints=web"
      - "traefik.http.routers.user-service.rule=Host(`user-service.${DOMAIN}`)"
    restart: always
    depends_on:
      - mongodb
  # ------------------- SERVICES ------------------
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    restart: always

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ service port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  mongodb_data:
  influxdb_data:
  influxdb_config:
  rabbitmq_data:
