version: "3.8"

services:
  # ------------------- APPS ------------------
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  # ------------------- SERVICES ------------------
  mongodb:
    image: mongo:latest # Or a specific version
    volumes:
      - mongodb_data:/data/db # Persist data
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management # Include management UI
    ports:
      - 5672:5672 # Default RabbitMQ port
      - 15672:15672 # Management UI port
volumes:
  mongodb_data: # Named volume for Mongo data
