import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/components/contexts/theme-provider";
import { AuthProvider } from "@/components/contexts/auth-context";
import { Noto_Sans as FontSans } from "next/font/google";
import { cookies } from "next/headers";

const fontSans = FontSans({
  subsets: ["latin", "latin-ext"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getTheme() {
  const cookieStore = cookies();
  const themeCookie = cookieStore.get("theme");
  const theme = themeCookie ? themeCookie.value : "dark";
  return theme;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = getTheme() as string;

  return (
    <html lang="en" className={theme} style={{ colorScheme: theme }}>
      <body className={fontSans.className}>
        <div className="w-screen max-w-full overflow-x-hidden">
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              storageKey="theme"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
