import type { Metadata } from "next";
import "./globals.css";

import { Noto_Sans as FontSans } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider";
import { cookies } from "next/headers";

const fontSans = FontSans({
  subsets: ["latin", "latin-ext"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getTheme() {
  const cookieStore = cookies()
  const themeCookie = cookieStore.get("theme")
  const theme = themeCookie ? themeCookie.value : "dark"
  return theme
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const theme = getTheme() as string

  return (
    <html lang="en" className={theme} style={{ colorScheme: theme }}>
      <body
        className={fontSans.className}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          storageKey="theme"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
