# Development stage
FROM golang:1.23
WORKDIR /app

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Expose port for the application (adjust if your app uses a different port)
EXPOSE 8080

# Command to run the application using air for live reloading
CMD ["air", "-c", ".air.toml"]

