FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . . 

# Use uvicorn with --reload for hot-reloading during development 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8083", "--reload"] 
