on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Run Tests in Web App
      working-directory: ./apps/web
      run: |
        npm ci
        npm run test

    - name: Run Tests in Snapshot Handler
      working-directory: ./apps/snapshot-handler
      run: go test ./...

    - name: Run Tests in Babybox Service
      working-directory: ./apps/babybox-service
      run: go test ./...

    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -p ${{secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: connect and pull
      run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && docker compose up --detach --build && exit"

    - name: cleanup
      run: rm -rf ~/.ssh